# to install this environment:
# micromamba create -f environment.yml -y
name: flood-wealth
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.12
- pip
- pip:
  - download-water-data # for downloading JRC surface water dataset
- ipykernel
- jupyter
- notebook
- fiona
- gdal
- pandas~=2.0
- numba
- geopandas
- openpyxl
- osmium-tool
- rasterio    
- rasterstats 
- bioconda::snakemake==7.18.2
- tqdm==4.62.3
- wget
- requests
- jq
- gsutil
- exactextract
- rasterio
