##########################
### Analysis Countries ###
##########################

# # ISO Codes for all analysis countries (108 total)
# iso_codes:
# - "BRA"
# - "IND"

# Limit to 92 countries where there are modelled and observed results.
iso_codes:
# - "AGO"
- "ALB"
# - "ARG"
- "ARM"
- "BDI"
- "BEN"
- "BFA"
- "BGD"
- "BGR"
- "BIH"
- "BLZ"
# - "BOL"
# - "BRA"
- "BTN"
- "BWA"
# - "CAF"
- "CIV"
- "CMR"
# - "COD"
- "COG"
# - "COL"
- "CRI"
- "DJI"
- "DOM"
# - "DZA"
- "ECU"
- "EGY"
- "ERI"
# - "ETH"
- "GEO"
- "GHA"
- "GIN"
- "GMB"
- "GNB"
- "GTM"
- "GUY"
- "HND"
- "HTI"
# - "IDN"
# - "IND"
- "JAM"
- "JOR"
# - "KAZ"
- "KEN"
- "KGZ"
- "KHM"
- "LAO"
- "LBR"
- "LKA"
- "LSO"
# - "MAR"
- "MDA"
- "MDG"
- "MEX"
- "MKD"
# - "MLI"
- "MNE"
# - "MOZ"
# - "MRT"
- "MWI"
- "MYS"
- "NER"
- "NGA"
- "NIC"
- "NPL"
# - "PAK"
# - "PER"
- "PHL"
- "PRY"
- "ROU"
- "RWA"
- "SEN"
- "SLE"
- "SLV"
- "SRB"
- "SUR"
- "SWZ"
# - "TCD"
- "TGO"
- "THA"
- "TJK"
- "TKM"
- "TUN"
- "TUR"
- "TZA"
- "UGA"
# - "UKR"
# - "UZB"
- "VNM"
# - "ZAF"
- "ZMB"
- "ZWE"

problem_iso_codes:
- "BRA"

# For GFD country name to ISO3 code conversion
gfd_code_mapping:
  AO: AGO
  AL: ALB
  AR: ARG
  AM: ARM
  BY: BDI
  BN: BEN
  UV: BFA
  BG: BGD
  BU: BGR
  BK: BIH
  BH: BLZ
  BL: BOL
  BR: BRA
  BT: BTN
  BC: BWA
  CT: CAF
  IV: CIV
  CM: CMR
  CG: COD
  CF: COG
  CO: COL
  CS: CRI
  DJ: DJI
  DR: DOM
  AG: DZA
  EC: ECU
  EG: EGY
  ER: ERI
  ET: ETH
  GG: GEO
  GH: GHA
  GV: GIN
  GA: GMB
  PU: GNB
  GT: GTM
  GY: GUY
  HO: HND
  HA: HTI
  ID: IDN
  IN: IND
  JM: JAM
  JO: JOR
  KZ: KAZ
  KE: KEN
  KG: KGZ
  CB: KHM
  LA: LAO
  LI: LBR
  CE: LKA
  LT: LSO
  MO: MAR
  MD: MDA
  MA: MDG
  MX: MEX
  MK: MKD
  ML: MLI
  MJ: MNE
  MZ: MOZ
  MR: MRT
  MI: MWI
  MY: MYS
  NG: NER
  NI: NGA
  NU: NIC
  NP: NPL
  PK: PAK
  PE: PER
  RP: PHL
  PA: PRY
  RO: ROU
  RW: RWA
  SG: SEN
  SL: SLE
  ES: SLV
  RB: SRB
  NS: SUR
  WZ: SWZ
  CD: TCD
  TO: TGO
  TH: THA
  TI: TJK
  TX: TKM
  TS: TUN
  TU: TUR
  TZ: TZA
  UG: UGA
  UP: UKR
  UZ: UZB
  VM: VNM
  SF: ZAF
  ZA: ZMB
  ZI: ZWE