##########################
### Analysis Countries ###
##########################

# # ISO Codes for all analysis countries (108 total)
# iso_codes:
# - "BRA"
# - "IND"

# Limit to 92 countries where there are modelled and observed results.
iso_codes:
- "AGO"
- "ALB"
- "ARG" # MEM
- "ARM"
- "BDI"
- "BEN"
- "BFA"
- "BGD"
- "BGR"
- "BIH"
- "BLZ"
- "BOL"
- "BRA" # MEM
- "BTN"
- "BWA"
- "CAF"
- "CIV"
- "CMR"
- "COD"
- "COG"
- "COL"
- "CRI"
- "DJI"
- "DOM"
- "DZA"
- "ECU"
- "EGY"
- "ERI"
- "ETH"
- "GEO"
- "GHA"
- "GIN"
- "GMB"
- "GNB"
- "GTM"
- "GUY"
- "HND"
- "HTI"
- "IDN" # MEM
- "IND" # MEM
- "JAM"
- "JOR"
- "KAZ" # MEM
- "KEN"
- "KGZ"
- "KHM"
- "LAO"
- "LBR"
- "LKA"
- "LSO"
- "MAR"
- "MDA"
- "MDG"
- "MEX" # MEM
- "MKD"
- "MLI"
- "MNE"
- "MOZ"
- "MRT"
- "MWI"
- "MYS"
- "NER"
- "NGA"
- "NIC"
- "NPL"
- "PAK"
- "PER"
- "PHL"
- "PRY"
- "ROU"
- "RWA"
- "SEN"
- "SLE"
- "SLV"
- "SRB"
- "SUR"
- "SWZ"
- "TCD"
- "TGO"
- "THA"
- "TJK"
- "TKM"
- "TUN"
- "TUR"
- "TZA"
- "UGA"
- "UKR"
- "UZB"
- "VNM"
- "ZAF" # MEM
- "ZMB"
- "ZWE"

problem_iso_codes:
- "BRA"