##########################
### Analysis Countries ###
##########################

# ISO Codes for all analysis countries (108 total)
iso_codes:
 - "AGO"
 - "ALB"
 - "ARG"
 - "ARM"
 - "AZE"   
 - "BDI"
 - "BEN"
 - "BFA"
 - "BGD"
 - "BGR"
 - "BIH"
 - "BLZ"
 - "BOL"
 - "BRA"
 - "BTN"
 - "BWA"
 - "CAF"
 - "CIV"
 - "CMR"
 - "COD"
 - "COG"
 - "COL"
 - "COM"
 - "CPV"
 - "CRI"
 - "DJI"
 - "DMA"
 - "DOM"
 - "DZA"
 - "ECU"
 - "EGY"
 - "ERI"
 - "ETH"
 - "GAB"
 - "GEO"
 - "GHA"
 - "GIN"
 - "GMB"
 - "GNB"
 - "GNQ"
 - "GRD"
 - "GTM"
 - "GUY"
 - "HND"
 - "HTI"
 - "IDN"
 - "IND"
 - "JAM"
 - "JOR"
 - "KAZ"
 - "KEN"
 - "KGZ"
 - "KHM"
 - "LAO"
 - "LBR"
 - "LBY"
 - "LCA"
 - "LKA"
 - "LSO"
 - "MAR"
 - "MDA"
 - "MDG"
 - "MDV"
 - "MEX"
 - "MKD"
 - "MLI"
 - "MNE"
 - "MNG"
 - "MOZ"
 - "MRT"
 - "MUS"
 - "MWI"
 - "MYS"
 - "NAM"
 - "NER"
 - "NGA"
 - "NIC"
 - "NPL"
 - "PAK"
 - "PER"
 - "PHL"
 - "PRY"
 - "ROU"
 - "RWA"
 - "SEN"
 - "SLE"
 - "SLV"
 - "SRB"
 - "STP"
 - "SUR"
 - "SWZ"
 - "TCD"
 - "TGO"
 - "THA"
 - "TJK"
 - "TKM"
 - "TLS"
 - "TUN"
 - "TUR"
 - "TZA"
 - "UGA"
 - "UKR"
 - "UZB"
 - "VCT"
 - "VNM"
 - "ZAF"
 - "ZMB"
 - "ZWE"